# Generated by Django 4.2.1 on 2023-05-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duaration',
            new_name='duration',
        ),
    ]
